virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
language: python
python:
    - "2.7"

install: "pip install -r requirements.txt"
script: "rm -r build dist; python setup.py install; python -m unittest discover"

